apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-{{ include "docs.fullname" . }}-ingress
  labels:
  {{- include "docs.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:036936483535:certificate/1d1d4794-b350-49e0-8136-5bef708f4b43  
    alb.ingress.kubernetes.io/group.name: prod-docs-ingress
    alb.ingress.kubernetes.io/group.order: "10"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/load-balancer-name: prod-docs-ingress
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    external-dns.alpha.kubernetes.io/hostname: docs.thedatareality.com

spec:
  defaultBackend:
    service:
      name: 'prod-{{ include "docs.fullname" . }}-service'
      port:
        number: 80
  ingressClassName: prod-safetylab-ingress